# Generated by Django 5.1.6 on 2025-02-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contact_id_alter_spamreport_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Global",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phoneNumber", models.CharField(max_length=30)),
                ("spamCount", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="SpamReport",
        ),
    ]
